NAME = megaphone

SOURCES = megaphone.cpp

CC = c++

FLAGS = -Wall -Wextra -Werror -std=c++98

OBJECTS = $(SOURCES:.cpp=.o)

%.o: %.cpp
	$(CC) $(FLAGS) -c $< -o $@

all: $(NAME)

$(NAME): $(OBJECTS)
	$(CC) $(OBJECTS) -o $(NAME)

clean:
	rm -f *.o

fclean: clean
	rm -f $(NAME)

re: fclean all